### PR TITLE
fix issue #116

### PR DESCRIPTION
**Pull request by MockingMagician**
## 📋 Description

Fixing issue for menu "show pb for desktop"

## 🗂 Type

- [x] 🚨 Bugfix

## 🔥 Severity

- [x] 💎 Non-Breaking Changes

## 🖥 Platforms

- [x] 🍏 macOS
- [x] 💾 Windows
- [x] 🐧 Linux

## 🛃 Tests

- [x] My changes have been tested manually.
- [x] My changes are covered by automated testing methods.

## 👨‍🎓 Miscellaneous

- [x] My changes follow the style guide.

### CODE REVIEW

**Comment by 4g0tt3nSou1** [comment]
@sidneys Can we get this merged in? Kinda a critical update if one can't open the app.

**Comment by MockingMagician** [comment]
> @sidneys Can we get this merged in? Kinda a critical update if one can't open the app.

@4g0tt3nSou1 if you are windows user you can simply download builds from this PR to https://ci.appveyor.com/project/sidneys/pb-for-desktop/builds/30419974/artifacts. If you are linux or darwin user, you can clone from this PR and build locally on your machine.

Hope this help and hope @sidneys his fine. Don't seeing him from a long time...

**Comment by NoiseEee** [comment]
Thanks @MockingMagician it was worth the build on Linux!

**Comment by sidneys** [comment]
@MockingMagician 

Thank you very much!
The fix will be deployed in v11.0.0, being released today.

Cheers,
S

**Pull request merged**
